### ISSUE TITLE
auth-js TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by ScottEAdams** [criipto/criipto-verify-react#10]
I cant seem to find the gh repo for criipto/auth-js which is throwing a bunch of undefined digest. Feel free to close if its already being dealt with internally.
```
criipto-auth.esm.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at i (criipto-auth.esm.js:1:25716)
    at criipto-verify-react.esm.js:1:8740
    at Generator.next (<anonymous>)
    at criipto-verify-react.esm.js:1:4399
    at new Promise (<anonymous>)
    at m (criipto-verify-react.esm.js:1:4160)
    at generatePKCE (criipto-verify-react.esm.js:1:8582)
    at criipto-verify-react.esm.js:1:13822
    at Generator.next (<anonymous>)
    at criipto-verify-react.esm.js:1:12811
```

**Comment by mickhansen** [comment]
@ScottEAdams what platform are you running on?

**Comment by mickhansen** [comment]
That error usually occurs if the browser does not have `subtle`: https://caniuse.com/mdn-api_subtlecrypto_digest

**Comment by ScottEAdams** [comment]
OSX - Version 104.0.5112.79 (Official Build) (x86_64)

**Comment by mickhansen** [comment]
@ScottEAdams `@criipto/auth-js` is now public: https://github.com/criipto/criipto-auth.js

**Comment by mickhansen** [comment]
> probably because of http (localhost)!

Hmm I have tested a lot on `http (localhost)` on my desktop, but perhaps the mobile device has different rules.

**Comment by ScottEAdams** [comment]
I think it may be because I am using a dev.blah-blah.se domain with hosts to 127.0.0.1. Will try with localhost.

**Comment by mickhansen** [comment]
> I think it may be because I am using a dev.blah-blah.se domain with hosts to 127.0.0.1. Will try with localhost.

Ah yes for non-`localhost` you need HTTPs to use SubtleCrypto i believe.

**Comment by ScottEAdams** [comment]
Yep, broke everything else in our setup but it got rid of the error. I will update to self-signed certificate https.
