### ISSUE TITLE
Property 'id_token' does not exist on type 'Result'.

### ISSUE THREAD

**Issue by ThomasLuuu** [criipto/criipto-verify-react#19]
I'm facing this issue when implementing the lib. 

```
    const {result} = useCriiptoVerify();
  if (result?.id_token) {
      return (
        <pre>
          {JSON.stringify(result.id_token, null, 2)}
        </pre>
      )
    } else {
      <React.Fragment>
        {result?.error ? (
          <p>
            An error occured: {result.error} ({result.error_description}). Please try again:
          </p>
        ) : null}
        <AuthMethodSelector />
      </React.Fragment>
    }
```
it gave me this error **Property 'id_token' does not exist on type 'Result'.
  Property 'id_token' does not exist on type 'Error'.ts(2339)**

**Comment by mickhansen** [comment]
Hi @ThomasLuuu,

Sounds like you are using typescript, in which case you need to type-narrow result by using `"id_token" in result`

**Comment by ThomasLuuu** [comment]
Hi @mickhansen, 
Thank you for your reply, I'm also facing these issues: 
1.  undefined Unable to resolve module @criipto/verify-react/dist/criipto-verify-react.css
2.Error: Unable to resolve module @criipto/auth-js/dist/index.css from C:\Users\***\node_modules\@criipto\verify-react\dist\criipto-verify-react.cjs.js: @criipto/auth-js/dist/index.css could not be found within the project or in these directories:
  node_modules\@criipto\verify-react\node_modules
  node_modules.
  I'm using typescript and React-native: 0.71.3

**Comment by mickhansen** [comment]
Hi @ThomasLuuu 

This library does not support react-native. We have a sample using React-Native/Expo here: https://github.com/criipto/verify-with-react-native-expo
We will have a seperate React-Native SDK in the future.
