### ISSUE TITLE
Override button logo and text

### ISSUE THREAD

**Issue by ScottEAdams** [criipto/criipto-verify-react#8]
It would be great if there was options to override the default buttons titles, logo (different colour if the button styling is overridden for example). Perhaps passed into the provider?

**Comment by mickhansen** [comment]
`AuthMethodButton` supports `children` as a prop, but are you working in the context of `AuthMethodSelector`? 
`logo` prop to `AuthMethodButton` is a good idea.

**Comment by ScottEAdams** [comment]
I was working with AuthMethodSelector but I can just map acr straight to button so this is perfect! Thanks :)

**Comment by mickhansen** [comment]
> I was working with AuthMethodSelector but I can just map acr straight to button so this is perfect! Thanks :)

Great, suggestions welcome on how one might modify logos and texts for buttons inside `AuthMethodSelector`. I couldn't see an immediate good way.

But `AuthMethodSelector` is pretty easy to replace as it doesn't do very much on it's own :)
