### ISSUE TITLE
Make AuthMethodButton styling optional

### ISSUE THREAD

**Issue by ScottEAdams** [criipto/criipto-verify-react#9]
Perhaps with a 'noStyle' prop or something?

```
const defaultClassName = props.noStyle ? '' : 'criipto-eid-btn';
const className = `${defaultClassName} ${acrValueToClassName(acrValue)}${props.className ? ` ${props.className}` : ''}`;
```

**Comment by mickhansen** [comment]
@ScottEAdams Are you finding it too cumbersome to just reset the CSS? I suppose that doesn't guard against us adding additional CSS.

**Comment by mickhansen** [comment]
If you refrain from importing the stylesheet from this library that should also do the trick.

**Comment by ScottEAdams** [comment]
My bad, first week back after summer. I had actually copied the styles into my components stylesheet yesterday whilst exploring. I thought it was the AuthMethodButton import!

**Comment by mickhansen** [comment]
> My bad, first week back after summer. I had actually copied the styles into my components stylesheet yesterday whilst exploring. I thought it was the AuthMethodButton import!

No worries! We appreciate the feedback.
